# -*- coding: utf-8 -*-
"""LAB2REP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M6TDxOTXh5q6x2KrsDydB5SqElXMjufH

# LAB2 REP

**My name is Muhammad Nasir Mehmood**
"""

print("Muhammad Nasir Mehmood!😁")

"""# LIST"""

list = [10,20,3,0,40,50,60,70,80,90,100]
print("Orignal List",list)
print("Sum:",sum(list))
print("Max",max(list))
print("Min",min(list))
list.append(111)
print("Appended List",list)
list.remove(111)
print("Updated List:",list)

while(True):
    print("😊")

"""# TUPLE"""

fruit = ("Apple","Mango","Grapes","Melon","Cherry")
print("First Elemnet:",fruit[1])
print("Last Elemnet:",fruit[-1])
new_list = list(fruit)
new_list[2] = "Orange"
print("Midfied List:",new_list)

"""# SET"""

set1 ={1,2,10,20}
set2 ={1,40,10,45}
print("UNION",set1|set2)
print("Intersection",set1&set2)
print("Difference",set1-set2)
set1.add(15)
set2.add(20)
print("Updated set1:",set1)
print("Updated set2:",set2)

"""# DICTIONARY"""

dic = {
    "Nasir":86,
    "Sadain":88,
    "Ehtisham":80,
    "Asdaq":76,
    "Saram":90
}
print("Keys",dic.keys())
print("Values",dic.values())
dic["Nasir"] = 90
print("Updated DICTIONARY",dic)
del dic["Saram"]
print("After Deletion:",dic)
print("Check if Nasir is in DIC:","Nasir" in dic)